/*
 * This file is generated by jOOQ.
 */
package in.onesoft.pos.jooq;


import in.onesoft.pos.jooq.tables.Companies;
import in.onesoft.pos.jooq.tables.CompanyScope;
import in.onesoft.pos.jooq.tables.ScopeRegistry;
import in.onesoft.pos.jooq.tables.Users;
import in.onesoft.pos.jooq.tables.records.CompaniesRecord;
import in.onesoft.pos.jooq.tables.records.CompanyScopeRecord;
import in.onesoft.pos.jooq.tables.records.ScopeRegistryRecord;
import in.onesoft.pos.jooq.tables.records.UsersRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<CompaniesRecord> COMPANIES_GSTIN_KEY = Internal.createUniqueKey(Companies.COMPANIES, DSL.name("companies_gstin_key"), new TableField[] { Companies.COMPANIES.GSTIN }, true);
    public static final UniqueKey<CompaniesRecord> COMPANIES_PKEY = Internal.createUniqueKey(Companies.COMPANIES, DSL.name("companies_pkey"), new TableField[] { Companies.COMPANIES.ID }, true);
    public static final UniqueKey<CompanyScopeRecord> COMPANY_SCOPE_PKEY = Internal.createUniqueKey(CompanyScope.COMPANY_SCOPE, DSL.name("company_scope_pkey"), new TableField[] { CompanyScope.COMPANY_SCOPE.COMPANY_ID }, true);
    public static final UniqueKey<ScopeRegistryRecord> SCOPE_REGISTRY_PKEY = Internal.createUniqueKey(ScopeRegistry.SCOPE_REGISTRY, DSL.name("scope_registry_pkey"), new TableField[] { ScopeRegistry.SCOPE_REGISTRY.SCOPE_ID }, true);
    public static final UniqueKey<UsersRecord> USERS_PKEY = Internal.createUniqueKey(Users.USERS, DSL.name("users_pkey"), new TableField[] { Users.USERS.ID }, true);
    public static final UniqueKey<UsersRecord> USERS_USERNAME_KEY = Internal.createUniqueKey(Users.USERS, DSL.name("users_username_key"), new TableField[] { Users.USERS.USERNAME }, true);
}
