/*
 * This file is generated by jOOQ.
 */
package in.onesoft.pos.jooq;


import in.onesoft.pos.jooq.tables.Companies;
import in.onesoft.pos.jooq.tables.CompanyScope;
import in.onesoft.pos.jooq.tables.ScopeRegistry;
import in.onesoft.pos.jooq.tables.Users;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.companies</code>.
     */
    public final Companies COMPANIES = Companies.COMPANIES;

    /**
     * The table <code>public.company_scope</code>.
     */
    public final CompanyScope COMPANY_SCOPE = CompanyScope.COMPANY_SCOPE;

    /**
     * The table <code>public.scope_registry</code>.
     */
    public final ScopeRegistry SCOPE_REGISTRY = ScopeRegistry.SCOPE_REGISTRY;

    /**
     * The table <code>public.users</code>.
     */
    public final Users USERS = Users.USERS;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Companies.COMPANIES,
            CompanyScope.COMPANY_SCOPE,
            ScopeRegistry.SCOPE_REGISTRY,
            Users.USERS
        );
    }
}
