/*
 * This file is generated by jOOQ.
 */
package in.onesoft.pos.jooq;


import in.onesoft.pos.jooq.tables.Companies;
import in.onesoft.pos.jooq.tables.CompanyScope;
import in.onesoft.pos.jooq.tables.ScopeRegistry;
import in.onesoft.pos.jooq.tables.Users;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.companies</code>.
     */
    public static final Companies COMPANIES = Companies.COMPANIES;

    /**
     * The table <code>public.company_scope</code>.
     */
    public static final CompanyScope COMPANY_SCOPE = CompanyScope.COMPANY_SCOPE;

    /**
     * The table <code>public.scope_registry</code>.
     */
    public static final ScopeRegistry SCOPE_REGISTRY = ScopeRegistry.SCOPE_REGISTRY;

    /**
     * The table <code>public.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
