/*
 * This file is generated by jOOQ.
 */
package in.onesoft.pos.jooq.tables;


import in.onesoft.pos.jooq.Keys;
import in.onesoft.pos.jooq.Public;
import in.onesoft.pos.jooq.tables.records.CompanyScopeRecord;

import java.time.LocalDateTime;
import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CompanyScope extends TableImpl<CompanyScopeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.company_scope</code>
     */
    public static final CompanyScope COMPANY_SCOPE = new CompanyScope();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CompanyScopeRecord> getRecordType() {
        return CompanyScopeRecord.class;
    }

    /**
     * The column <code>public.company_scope.company_id</code>.
     */
    public final TableField<CompanyScopeRecord, String> COMPANY_ID = createField(DSL.name("company_id"), SQLDataType.VARCHAR(19).nullable(false), this, "");

    /**
     * The column <code>public.company_scope.scope_id</code>.
     */
    public final TableField<CompanyScopeRecord, String> SCOPE_ID = createField(DSL.name("scope_id"), SQLDataType.CHAR(7).nullable(false), this, "");

    /**
     * The column <code>public.company_scope.created_at</code>.
     */
    public final TableField<CompanyScopeRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.LOCALDATETIME)), this, "");

    private CompanyScope(Name alias, Table<CompanyScopeRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private CompanyScope(Name alias, Table<CompanyScopeRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.company_scope</code> table reference
     */
    public CompanyScope(String alias) {
        this(DSL.name(alias), COMPANY_SCOPE);
    }

    /**
     * Create an aliased <code>public.company_scope</code> table reference
     */
    public CompanyScope(Name alias) {
        this(alias, COMPANY_SCOPE);
    }

    /**
     * Create a <code>public.company_scope</code> table reference
     */
    public CompanyScope() {
        this(DSL.name("company_scope"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<CompanyScopeRecord> getPrimaryKey() {
        return Keys.COMPANY_SCOPE_PKEY;
    }

    @Override
    public CompanyScope as(String alias) {
        return new CompanyScope(DSL.name(alias), this);
    }

    @Override
    public CompanyScope as(Name alias) {
        return new CompanyScope(alias, this);
    }

    @Override
    public CompanyScope as(Table<?> alias) {
        return new CompanyScope(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public CompanyScope rename(String name) {
        return new CompanyScope(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CompanyScope rename(Name name) {
        return new CompanyScope(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public CompanyScope rename(Table<?> name) {
        return new CompanyScope(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CompanyScope where(Condition condition) {
        return new CompanyScope(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CompanyScope where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CompanyScope where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CompanyScope where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CompanyScope where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CompanyScope where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CompanyScope where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CompanyScope where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CompanyScope whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CompanyScope whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
