/*
 * This file is generated by jOOQ.
 */
package in.onesoft.pos.jooq.tables;


import in.onesoft.pos.jooq.Keys;
import in.onesoft.pos.jooq.Public;
import in.onesoft.pos.jooq.tables.records.CompaniesRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Companies extends TableImpl<CompaniesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.companies</code>
     */
    public static final Companies COMPANIES = new Companies();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CompaniesRecord> getRecordType() {
        return CompaniesRecord.class;
    }

    /**
     * The column <code>public.companies.id</code>.
     */
    public final TableField<CompaniesRecord, String> ID = createField(DSL.name("id"), SQLDataType.VARCHAR(19).nullable(false), this, "");

    /**
     * The column <code>public.companies.scope_id</code>.
     */
    public final TableField<CompaniesRecord, String> SCOPE_ID = createField(DSL.name("scope_id"), SQLDataType.CHAR(7).nullable(false), this, "");

    /**
     * The column <code>public.companies.name</code>.
     */
    public final TableField<CompaniesRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(150).nullable(false), this, "");

    /**
     * The column <code>public.companies.gstin</code>.
     */
    public final TableField<CompaniesRecord, String> GSTIN = createField(DSL.name("gstin"), SQLDataType.VARCHAR(15), this, "");

    /**
     * The column <code>public.companies.phone</code>.
     */
    public final TableField<CompaniesRecord, String> PHONE = createField(DSL.name("phone"), SQLDataType.VARCHAR(15), this, "");

    /**
     * The column <code>public.companies.email</code>.
     */
    public final TableField<CompaniesRecord, String> EMAIL = createField(DSL.name("email"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>public.companies.plan_type</code>.
     */
    public final TableField<CompaniesRecord, String> PLAN_TYPE = createField(DSL.name("plan_type"), SQLDataType.VARCHAR(20).defaultValue(DSL.field(DSL.raw("'BASIC'::character varying"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.companies.is_active</code>.
     */
    public final TableField<CompaniesRecord, Boolean> IS_ACTIVE = createField(DSL.name("is_active"), SQLDataType.BOOLEAN.defaultValue(DSL.field(DSL.raw("true"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.companies.created_at</code>.
     */
    public final TableField<CompaniesRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.LOCALDATETIME)), this, "");

    private Companies(Name alias, Table<CompaniesRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Companies(Name alias, Table<CompaniesRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.companies</code> table reference
     */
    public Companies(String alias) {
        this(DSL.name(alias), COMPANIES);
    }

    /**
     * Create an aliased <code>public.companies</code> table reference
     */
    public Companies(Name alias) {
        this(alias, COMPANIES);
    }

    /**
     * Create a <code>public.companies</code> table reference
     */
    public Companies() {
        this(DSL.name("companies"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<CompaniesRecord> getPrimaryKey() {
        return Keys.COMPANIES_PKEY;
    }

    @Override
    public List<UniqueKey<CompaniesRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.COMPANIES_GSTIN_KEY);
    }

    @Override
    public Companies as(String alias) {
        return new Companies(DSL.name(alias), this);
    }

    @Override
    public Companies as(Name alias) {
        return new Companies(alias, this);
    }

    @Override
    public Companies as(Table<?> alias) {
        return new Companies(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Companies rename(String name) {
        return new Companies(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Companies rename(Name name) {
        return new Companies(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Companies rename(Table<?> name) {
        return new Companies(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Companies where(Condition condition) {
        return new Companies(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Companies where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Companies where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Companies where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Companies where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Companies where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Companies where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Companies where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Companies whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Companies whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
