/*
 * This file is generated by jOOQ.
 */
package in.onesoft.pos.jooq.tables;


import in.onesoft.pos.jooq.Keys;
import in.onesoft.pos.jooq.Public;
import in.onesoft.pos.jooq.tables.records.ScopeRegistryRecord;

import java.time.LocalDateTime;
import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ScopeRegistry extends TableImpl<ScopeRegistryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.scope_registry</code>
     */
    public static final ScopeRegistry SCOPE_REGISTRY = new ScopeRegistry();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ScopeRegistryRecord> getRecordType() {
        return ScopeRegistryRecord.class;
    }

    /**
     * The column <code>public.scope_registry.scope_id</code>.
     */
    public final TableField<ScopeRegistryRecord, String> SCOPE_ID = createField(DSL.name("scope_id"), SQLDataType.CHAR(7).nullable(false), this, "");

    /**
     * The column <code>public.scope_registry.db_key</code>.
     */
    public final TableField<ScopeRegistryRecord, String> DB_KEY = createField(DSL.name("db_key"), SQLDataType.VARCHAR(20).nullable(false), this, "");

    /**
     * The column <code>public.scope_registry.db_url</code>.
     */
    public final TableField<ScopeRegistryRecord, String> DB_URL = createField(DSL.name("db_url"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.scope_registry.db_username</code>.
     */
    public final TableField<ScopeRegistryRecord, String> DB_USERNAME = createField(DSL.name("db_username"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.scope_registry.db_password</code>.
     */
    public final TableField<ScopeRegistryRecord, String> DB_PASSWORD = createField(DSL.name("db_password"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>public.scope_registry.is_active</code>.
     */
    public final TableField<ScopeRegistryRecord, Boolean> IS_ACTIVE = createField(DSL.name("is_active"), SQLDataType.BOOLEAN.defaultValue(DSL.field(DSL.raw("true"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.scope_registry.created_at</code>.
     */
    public final TableField<ScopeRegistryRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.LOCALDATETIME)), this, "");

    private ScopeRegistry(Name alias, Table<ScopeRegistryRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ScopeRegistry(Name alias, Table<ScopeRegistryRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.scope_registry</code> table reference
     */
    public ScopeRegistry(String alias) {
        this(DSL.name(alias), SCOPE_REGISTRY);
    }

    /**
     * Create an aliased <code>public.scope_registry</code> table reference
     */
    public ScopeRegistry(Name alias) {
        this(alias, SCOPE_REGISTRY);
    }

    /**
     * Create a <code>public.scope_registry</code> table reference
     */
    public ScopeRegistry() {
        this(DSL.name("scope_registry"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<ScopeRegistryRecord> getPrimaryKey() {
        return Keys.SCOPE_REGISTRY_PKEY;
    }

    @Override
    public ScopeRegistry as(String alias) {
        return new ScopeRegistry(DSL.name(alias), this);
    }

    @Override
    public ScopeRegistry as(Name alias) {
        return new ScopeRegistry(alias, this);
    }

    @Override
    public ScopeRegistry as(Table<?> alias) {
        return new ScopeRegistry(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ScopeRegistry rename(String name) {
        return new ScopeRegistry(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ScopeRegistry rename(Name name) {
        return new ScopeRegistry(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ScopeRegistry rename(Table<?> name) {
        return new ScopeRegistry(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ScopeRegistry where(Condition condition) {
        return new ScopeRegistry(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ScopeRegistry where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ScopeRegistry where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ScopeRegistry where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ScopeRegistry where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ScopeRegistry where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ScopeRegistry where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ScopeRegistry where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ScopeRegistry whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ScopeRegistry whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
