/*
 * This file is generated by jOOQ.
 */
package in.onesoft.pos.jooq.tables.records;


import in.onesoft.pos.jooq.tables.Companies;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CompaniesRecord extends UpdatableRecordImpl<CompaniesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.companies.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.companies.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.companies.scope_id</code>.
     */
    public void setScopeId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.companies.scope_id</code>.
     */
    public String getScopeId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.companies.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.companies.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.companies.gstin</code>.
     */
    public void setGstin(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.companies.gstin</code>.
     */
    public String getGstin() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.companies.phone</code>.
     */
    public void setPhone(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.companies.phone</code>.
     */
    public String getPhone() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.companies.email</code>.
     */
    public void setEmail(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.companies.email</code>.
     */
    public String getEmail() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.companies.plan_type</code>.
     */
    public void setPlanType(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.companies.plan_type</code>.
     */
    public String getPlanType() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.companies.is_active</code>.
     */
    public void setIsActive(Boolean value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.companies.is_active</code>.
     */
    public Boolean getIsActive() {
        return (Boolean) get(7);
    }

    /**
     * Setter for <code>public.companies.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.companies.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CompaniesRecord
     */
    public CompaniesRecord() {
        super(Companies.COMPANIES);
    }

    /**
     * Create a detached, initialised CompaniesRecord
     */
    public CompaniesRecord(String id, String scopeId, String name, String gstin, String phone, String email, String planType, Boolean isActive, LocalDateTime createdAt) {
        super(Companies.COMPANIES);

        setId(id);
        setScopeId(scopeId);
        setName(name);
        setGstin(gstin);
        setPhone(phone);
        setEmail(email);
        setPlanType(planType);
        setIsActive(isActive);
        setCreatedAt(createdAt);
        resetChangedOnNotNull();
    }
}
