/*
 * This file is generated by jOOQ.
 */
package in.onesoft.pos.jooq.tables.records;


import in.onesoft.pos.jooq.tables.CompanyScope;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CompanyScopeRecord extends UpdatableRecordImpl<CompanyScopeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.company_scope.company_id</code>.
     */
    public void setCompanyId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.company_scope.company_id</code>.
     */
    public String getCompanyId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.company_scope.scope_id</code>.
     */
    public void setScopeId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.company_scope.scope_id</code>.
     */
    public String getScopeId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.company_scope.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.company_scope.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CompanyScopeRecord
     */
    public CompanyScopeRecord() {
        super(CompanyScope.COMPANY_SCOPE);
    }

    /**
     * Create a detached, initialised CompanyScopeRecord
     */
    public CompanyScopeRecord(String companyId, String scopeId, LocalDateTime createdAt) {
        super(CompanyScope.COMPANY_SCOPE);

        setCompanyId(companyId);
        setScopeId(scopeId);
        setCreatedAt(createdAt);
        resetChangedOnNotNull();
    }
}
