/*
 * This file is generated by jOOQ.
 */
package in.onesoft.pos.jooq.tables.records;


import in.onesoft.pos.jooq.tables.ScopeRegistry;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ScopeRegistryRecord extends UpdatableRecordImpl<ScopeRegistryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.scope_registry.scope_id</code>.
     */
    public void setScopeId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.scope_registry.scope_id</code>.
     */
    public String getScopeId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.scope_registry.db_key</code>.
     */
    public void setDbKey(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.scope_registry.db_key</code>.
     */
    public String getDbKey() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.scope_registry.db_url</code>.
     */
    public void setDbUrl(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.scope_registry.db_url</code>.
     */
    public String getDbUrl() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.scope_registry.db_username</code>.
     */
    public void setDbUsername(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.scope_registry.db_username</code>.
     */
    public String getDbUsername() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.scope_registry.db_password</code>.
     */
    public void setDbPassword(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.scope_registry.db_password</code>.
     */
    public String getDbPassword() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.scope_registry.is_active</code>.
     */
    public void setIsActive(Boolean value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.scope_registry.is_active</code>.
     */
    public Boolean getIsActive() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>public.scope_registry.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.scope_registry.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ScopeRegistryRecord
     */
    public ScopeRegistryRecord() {
        super(ScopeRegistry.SCOPE_REGISTRY);
    }

    /**
     * Create a detached, initialised ScopeRegistryRecord
     */
    public ScopeRegistryRecord(String scopeId, String dbKey, String dbUrl, String dbUsername, String dbPassword, Boolean isActive, LocalDateTime createdAt) {
        super(ScopeRegistry.SCOPE_REGISTRY);

        setScopeId(scopeId);
        setDbKey(dbKey);
        setDbUrl(dbUrl);
        setDbUsername(dbUsername);
        setDbPassword(dbPassword);
        setIsActive(isActive);
        setCreatedAt(createdAt);
        resetChangedOnNotNull();
    }
}
