/*
 * This file is generated by jOOQ.
 */
package in.onesoft.pos.jooq.tables.records;


import in.onesoft.pos.jooq.tables.Users;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UsersRecord extends UpdatableRecordImpl<UsersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.users.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.users.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.users.scope_id</code>.
     */
    public void setScopeId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.users.scope_id</code>.
     */
    public String getScopeId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.users.company_id</code>.
     */
    public void setCompanyId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.users.company_id</code>.
     */
    public String getCompanyId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.users.username</code>.
     */
    public void setUsername(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.users.username</code>.
     */
    public String getUsername() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.users.password_hash</code>.
     */
    public void setPasswordHash(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.users.password_hash</code>.
     */
    public String getPasswordHash() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.users.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.users.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UsersRecord
     */
    public UsersRecord() {
        super(Users.USERS);
    }

    /**
     * Create a detached, initialised UsersRecord
     */
    public UsersRecord(String id, String scopeId, String companyId, String username, String passwordHash, LocalDateTime createdAt) {
        super(Users.USERS);

        setId(id);
        setScopeId(scopeId);
        setCompanyId(companyId);
        setUsername(username);
        setPasswordHash(passwordHash);
        setCreatedAt(createdAt);
        resetChangedOnNotNull();
    }
}
